//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_CRUD.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ETable
    {

        public int EId { get; set; }
        [Required(ErrorMessage ="Required")]
        public string EName { get; set; }

        [Required(ErrorMessage = "Required")]
        public string EAddress { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> Eage { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Esallery { get; set; }
    }
}
